blueprint:
  name: DHW Control with Legionella Protection
  description: 'Control Domestic Hot Water (DHW) temperature based on Day/Night schedules
    for Weekdays and Weekends. Includes a weekly Legionella protection cycle that
    raises the temperature to a specified level for a set duration.

    '
  domain: automation
  input:
    dhw_entity:
      name: DHW Entity
      description: The entity to control (climate or water_heater).
      selector:
        entity:
          domain:
          - climate
          - water_heater
          multiple: false
          reorder: false
    day_temp:
      name: Day (Comfort) Temperature
      description: Target temperature during active hours.
      default: 50
      selector:
        number:
          min: 20.0
          max: 80.0
          step: 0.5
          unit_of_measurement: °C
          mode: slider
    night_temp:
      name: Night (Eco) Temperature
      description: Target temperature during inactive hours.
      default: 40
      selector:
        number:
          min: 20.0
          max: 80.0
          step: 0.5
          unit_of_measurement: °C
          mode: slider
    weekday_day_start:
      name: Weekday Day Start
      description: Time when Day mode starts on weekdays (Mon-Fri).
      default: 06:00:00
      selector:
        time: {}
    weekday_day_end:
      name: Weekday Day End
      description: Time when Day mode ends on weekdays (Mon-Fri).
      default: '22:00:00'
      selector:
        time: {}
    weekend_day_start:
      name: Weekend Day Start
      description: Time when Day mode starts on weekends (Sat-Sun).
      default: 07:00:00
      selector:
        time: {}
    weekend_day_end:
      name: Weekend Day End
      description: Time when Day mode ends on weekends (Sat-Sun).
      default: '23:00:00'
      selector:
        time: {}
    legionella_enabled:
      name: Enable Legionella Protection
      description: Enable the weekly anti-legionella cycle.
      default: true
      selector:
        boolean: {}
    legionella_temp:
      name: Legionella Temperature
      description: Target temperature for the Legionella cycle.
      default: 60
      selector:
        number:
          min: 55.0
          max: 80.0
          step: 0.5
          unit_of_measurement: °C
          mode: slider
    legionella_day:
      name: Legionella Day
      description: Day of the week to run the Legionella cycle.
      default: sun
      selector:
        select:
          options:
          - label: Monday
            value: mon
          - label: Tuesday
            value: tue
          - label: Wednesday
            value: wed
          - label: Thursday
            value: thu
          - label: Friday
            value: fri
          - label: Saturday
            value: sat
          - label: Sunday
            value: sun
          multiple: false
          sort: false
          custom_value: false
    legionella_start_time:
      name: Legionella Start Time
      description: Time to start the Legionella cycle.
      default: 04:00:00
      selector:
        time: {}
    legionella_duration:
      name: Legionella Duration
      description: How long to maintain the Legionella temperature.
      default:
        hours: 1
        minutes: 0
        seconds: 0
      selector:
        duration: {}
    notifications_enabled:
      name: Enable Notifications
      description: Send notifications when mode changes or Legionella cycle runs.
      default: true
      selector:
        boolean: {}
  source_url: https://github.com/lachyn/ha-blueprints/blob/main/dhw_control.yaml
variables:
  dhw_entity: !input dhw_entity
  day_temp: !input day_temp
  night_temp: !input night_temp
  weekday_day_start: !input weekday_day_start
  weekday_day_end: !input weekday_day_end
  weekend_day_start: !input weekend_day_start
  weekend_day_end: !input weekend_day_end
  legionella_enabled: !input legionella_enabled
  legionella_temp: !input legionella_temp
  legionella_day: !input legionella_day
  legionella_duration: !input legionella_duration
  notifications_enabled: !input notifications_enabled
trigger:
- platform: time
  at: !input weekday_day_start
  id: schedule
- platform: time
  at: !input weekday_day_end
  id: schedule
- platform: time
  at: !input weekend_day_start
  id: schedule
- platform: time
  at: !input weekend_day_end
  id: schedule
- platform: time
  at: !input legionella_start_time
  id: legionella
action:
- choose:
  - conditions:
    - condition: trigger
      id: legionella
    - condition: template
      value_template: '{{ legionella_enabled }}'
    - condition: template
      value_template: '{{ now().strftime(''%a'').lower() == legionella_day }}'
    sequence:
    - service: '{{ ''climate.set_temperature'' if dhw_entity.startswith(''climate.'')
        else ''water_heater.set_temperature'' }}'
      target:
        entity_id: !input dhw_entity
      data:
        temperature: "{{ legionella_temp | float }}"
    - if:
      - condition: template
        value_template: '{{ notifications_enabled }}'
      then:
      - service: notify.notify
        data:
          title: "\U0001F9A0 Legionella Cycle Started"
          message: DHW temperature set to {{ legionella_temp }}°C for protection.
    - delay: !input legionella_duration
    - variables:
        restore_temp: >-
          {% set t = now().time() %}
          {% set d = now().weekday() %}
          {% set is_weekend = d >= 5 %}
          {% if is_weekend %}
            {% set start = strptime(weekend_day_start, '%H:%M:%S').time() %}
            {% set end = strptime(weekend_day_end, '%H:%M:%S').time() %}
          {% else %}
            {% set start = strptime(weekday_day_start, '%H:%M:%S').time() %}
            {% set end = strptime(weekday_day_end, '%H:%M:%S').time() %}
          {% endif %}
          {% if start < end %}
            {% set is_active = start <= t < end %}
          {% else %}
            {% set is_active = start <= t or t < end %}
          {% endif %}
          {{ (day_temp if is_active else night_temp) | float }}
    - alias: Restore Schedule after Legionella
      service: '{{ ''climate.set_temperature'' if dhw_entity.startswith(''climate.'')
        else ''water_heater.set_temperature'' }}'
      target:
        entity_id: !input dhw_entity
      data:
        temperature: "{{ restore_temp | float }}"
    - if:
      - condition: template
        value_template: '{{ notifications_enabled }}'
      then:
      - service: notify.notify
        data:
          title: ✅ Legionella Cycle Finished
          message: DHW temperature restored to schedule ({{ restore_temp }}°C).
  - conditions:
    - condition: trigger
      id: schedule
    sequence:
    - variables:
        schedule_temp: >-
          {% set t = now().time() %}
          {% set d = now().weekday() %}
          {% set is_weekend = d >= 5 %}
          {% if is_weekend %}
            {% set start = strptime(weekend_day_start, '%H:%M:%S').time() %}
            {% set end = strptime(weekend_day_end, '%H:%M:%S').time() %}
          {% else %}
            {% set start = strptime(weekday_day_start, '%H:%M:%S').time() %}
            {% set end = strptime(weekday_day_end, '%H:%M:%S').time() %}
          {% endif %}
          {% if start < end %}
            {% set is_active = start <= t < end %}
          {% else %}
            {% set is_active = start <= t or t < end %}
          {% endif %}
          {{ (day_temp if is_active else night_temp) | float }}
    - service: '{{ ''climate.set_temperature'' if dhw_entity.startswith(''climate.'')
        else ''water_heater.set_temperature'' }}'
      target:
        entity_id: !input dhw_entity
      data:
        temperature: "{{ schedule_temp | float }}"
    - if:
      - condition: template
        value_template: '{{ notifications_enabled }}'
      then:
      - service: notify.notify
        data:
          title: "\U0001F6BF DHW Schedule Update"
          message: DHW temperature set to {{ schedule_temp }}°C.
mode: single
