blueprint:
  name: Night Mode Heating Control (OTGateway)
  description: Automatically sets lower heating temperature at specified time and
    restores original temperature at another time. Useful for nighttime heating optimization
    with OTGateway. Supports different schedules for different days of the week.
  domain: automation
  author: lachyn
  source_url: https://github.com/lachyn/ha-blueprints/blob/main/night_mode_heating.yaml
  input:
    climate_entity:
      name: Climate Entity
      description: The climate entity for heating control (e.g., climate.opentherm_heating)
      selector:
        entity:
          multiple: false
          filter:
          - domain:
            - climate
          reorder: false
    weekday_night_start_time:
      name: Weekday Night Start Time (Mon-Fri)
      description: Time when night mode should activate on weekdays
      selector:
        time: {}
      default: '23:30'
    weekday_night_end_time:
      name: Weekday Night End Time (Mon-Fri)
      description: Time when night mode should deactivate on weekdays
      selector:
        time: {}
      default: 05:30
    weekend_night_start_time:
      name: Weekend Night Start Time (Sat-Sun)
      description: Time when night mode should activate on weekends
      selector:
        time: {}
      default: 00:00
    weekend_night_end_time:
      name: Weekend Night End Time (Sat-Sun)
      description: Time when night mode should deactivate on weekends
      selector:
        time: {}
      default: 08:00
    night_temperature:
      name: Night Temperature
      description: Target temperature for night mode
      selector:
        number:
          min: 10.0
          max: 30.0
          step: 0.5
          unit_of_measurement: °C
          mode: slider
      default: 16
    day_temperature:
      name: Day Temperature
      description: Target temperature for day mode (normal operation)
      selector:
        number:
          min: 10.0
          max: 30.0
          step: 0.5
          unit_of_measurement: °C
          mode: slider
      default: 21
    notifications_enabled:
      name: Enable Notifications
      description: Send notifications when mode changes
      selector:
        boolean: {}
      default: true
variables:
  climate_entity: !input climate_entity
  weekday_night_start_time: !input weekday_night_start_time
  weekday_night_end_time: !input weekday_night_end_time
  weekend_night_start_time: !input weekend_night_start_time
  weekend_night_end_time: !input weekend_night_end_time
  night_temperature: !input night_temperature
  day_temperature: !input day_temperature
  notifications_enabled: !input notifications_enabled
  is_weekday: '{{ now().weekday() < 5 }}'
trigger:
- platform: time
  at: !input weekday_night_start_time
  id: activate_night_mode_weekday
- platform: time
  at: !input weekday_night_end_time
  id: deactivate_night_mode_weekday
- platform: time
  at: !input weekend_night_start_time
  id: activate_night_mode_weekend
- platform: time
  at: !input weekend_night_end_time
  id: deactivate_night_mode_weekend
condition:
- condition: template
  value_template: '{{ states(climate_entity) != ''unavailable'' and states(climate_entity)
    != ''unknown'' }}'
action:
- choose:
  - conditions:
    - condition: trigger
      id:
      - activate_night_mode_weekday
    - condition: template
      value_template: '{{ is_weekday }}'
    sequence:
    - service: climate.set_temperature
      target:
        entity_id: '{{ climate_entity }}'
      data:
        temperature: '{{ night_temperature }}'
    - if:
      - condition: template
        value_template: '{{ notifications_enabled }}'
      then:
      - service: notify.notify
        data:
          title: "\U0001F319 Weekday Night Mode Activated"
          message: Heating temperature set to {{ night_temperature }}°C (Weekday)
  - conditions:
    - condition: trigger
      id:
      - activate_night_mode_weekend
    - condition: template
      value_template: '{{ not is_weekday }}'
    sequence:
    - service: climate.set_temperature
      target:
        entity_id: '{{ climate_entity }}'
      data:
        temperature: '{{ night_temperature }}'
    - if:
      - condition: template
        value_template: '{{ notifications_enabled }}'
      then:
      - service: notify.notify
        data:
          title: "\U0001F319 Weekend Night Mode Activated"
          message: Heating temperature set to {{ night_temperature }}°C (Weekend)
  - conditions:
    - condition: trigger
      id:
      - deactivate_night_mode_weekday
    - condition: template
      value_template: '{{ is_weekday }}'
    sequence:
    - service: climate.set_temperature
      target:
        entity_id: '{{ climate_entity }}'
      data:
        temperature: '{{ day_temperature }}'
    - if:
      - condition: template
        value_template: '{{ notifications_enabled }}'
      then:
      - service: notify.notify
        data:
          title: ☀️ Weekday Day Mode Activated
          message: Heating temperature set to {{ day_temperature }}°C (Weekday)
  - conditions:
    - condition: trigger
      id:
      - deactivate_night_mode_weekend
    - condition: template
      value_template: '{{ not is_weekday }}'
    sequence:
    - service: climate.set_temperature
      target:
        entity_id: '{{ climate_entity }}'
      data:
        temperature: '{{ day_temperature }}'
    - if:
      - condition: template
        value_template: '{{ notifications_enabled }}'
      then:
      - service: notify.notify
        data:
          title: ☀️ Weekend Day Mode Activated
          message: Heating temperature set to {{ day_temperature }}°C (Weekend)
mode: single